sudo: required

services:
  - docker

language: node_js

node_js:
  - "8"

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login -u _ --password=$HEROKU_API_KEY registry.heroku.com

script:
  - docker build -t herokuimage .

deploy:
  - provider: script
    script:
        docker tag herokuimage registry.heroku.com/$HEROKU_APP_NAME/web;
        docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master

email:
  - ddydeveloper@gmail.com