# sudo: required
dist: trusty

services:
  - docker

language: node_js

node_js:
  - "8"

addons:
  sonarcloud:
    organization: $SONAR_ORG_KEY
    token:
      secure: $SONAR_TOKEN

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login -u _ --password=$HEROKU_API_KEY registry.heroku.com

script:
  - sonar-scanner
  - docker build -t herokuimage .

deploy:
  - provider: script
    script:
        docker tag herokuimage registry.heroku.com/$HEROKU_APP_NAME/web;
        docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master

email:
  - ddydeveloper@gmail.com

 notifications:
  slack:
    rooms:
      - spbdotnet:LQchHl5OfFOciFmEI9TpUpvP#general
      - spbdotnet:LQchHl5OfFOciFmEI9TpUpvP#random
